"""Tests for :mod:`app.handlers.user.buy` — buy flow + inbound selection."""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, MagicMock

import pytest

from app.config import settings
from app.db.repos.users import User
from app.handlers.user import buy as buy_module
from app.keyboards.user import BuyCB, InboundCB
from app.services.inbounds import InboundOption
from app.xui import XuiError


def _user(user_id=1, tg_id=1, is_admin=False):
    return User(
        id=user_id, tg_id=tg_id, username="u", first_name="X",
        is_admin=is_admin, created_at="2025",
    )


def _state(data: dict | None = None):
    """Build a mock FSMContext, optionally pre-seeded with state data."""
    s = AsyncMock()
    s.get_data = AsyncMock(return_value=data or {})
    s.update_data = AsyncMock()
    s.set_state = AsyncMock()
    s.clear = AsyncMock()
    return s


def _stub_inbounds(*ids: int) -> list[InboundOption]:
    """Build an `InboundOption` list with the given ids (remarks autogenerated)."""
    return [
        InboundOption(id=i, remark=f"srv-{i}", port=443 + i, enabled=True)
        for i in ids
    ]


@pytest.fixture(autouse=True)
def _clear_inbounds_cache():
    """Drop the inbounds service cache between tests to avoid leakage."""
    from app.services import inbounds as inb

    inb.clear_cache()
    yield
    inb.clear_cache()


# ---------------------------------------------------------------------- #
# cb_open — show plan list
# ---------------------------------------------------------------------- #


async def test_cb_open_no_plans(file_db, mock_bot):
    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_open(cb, state)
    cb.message.edit_text.assert_awaited()


async def test_cb_open_with_plans(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        await make_plan(conn)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_open(cb, state)
    cb.message.edit_text.assert_awaited()


# ---------------------------------------------------------------------- #
# cb_pick_plan — single vs multi inbound routing
# ---------------------------------------------------------------------- #


async def test_cb_pick_plan_single_inbound_skips_to_confirm(
    file_db, make_plan, monkeypatch
):
    """A plan with exactly one inbound auto-skips the selection step."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    # Panel returns one matching inbound — the resolver looks up its remark.
    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)

    # State writes: inbound_id is pinned and no options stored (single-inbound path).
    state.update_data.assert_awaited()
    last_kwargs = state.update_data.await_args.kwargs
    assert last_kwargs["inbound_id"] == 1
    assert last_kwargs.get("inbound_options") is None
    # The confirmation card was rendered (edit_text called).
    cb.message.edit_text.assert_awaited()


async def test_cb_pick_plan_multi_inbound_shows_selector(
    file_db, make_plan, monkeypatch
):
    """A plan with N>1 inbounds enters choosing_inbound with the multi-option kb."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1, 2, 99)),  # 99 is not in plan
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)

    # Stored options should be filtered to inbound ids 1 and 2 only.
    last_kwargs = state.update_data.await_args.kwargs
    stored_options = last_kwargs["inbound_options"]
    assert {o["id"] for o in stored_options} == {1, 2}
    assert last_kwargs["inbound_id"] == 0  # not yet picked


async def test_cb_pick_plan_no_inbounds_misconfigured(file_db, make_plan, monkeypatch):
    """A plan with zero inbounds yields an alert and no state advance."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[])  # explicit: no inbounds

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)
    # Alert was shown.
    cb.answer.assert_awaited()
    args, kwargs = cb.answer.call_args
    assert kwargs.get("show_alert") is True


async def test_cb_pick_plan_with_existing_promo_in_state(
    file_db, make_plan, make_promo, monkeypatch
):
    """Picking a plan preserves a promo_id already in FSM."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])
        promo = await make_promo(conn, code="X")

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state({"promo_id": promo.id})
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)
    last_kwargs = state.update_data.await_args.kwargs
    assert last_kwargs["promo_id"] == promo.id


async def test_cb_pick_plan_unknown_or_inactive(file_db):
    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    cb_data = BuyCB(action="plan", plan_id=999)
    await buy_module.cb_pick_plan(cb, cb_data, state)
    cb.answer.assert_awaited_once()


async def test_cb_pick_plan_xui_unavailable_multi(file_db, make_plan, monkeypatch):
    """When the panel fails on a multi-inbound plan the user sees an alert."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(side_effect=XuiError("down")),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True


# ---------------------------------------------------------------------- #
# cb_pick_inbound — inbound selection step
# ---------------------------------------------------------------------- #


async def test_cb_pick_inbound_valid(file_db, make_plan):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state({"inbound_options": [{"id": 1, "remark": "DE", "port": 443, "enabled": True}]})
    await buy_module.cb_pick_inbound(
        cb,
        InboundCB(action="pick", plan_id=plan.id, inbound_id=1),
        state,
    )
    last = state.update_data.await_args.kwargs
    assert last["inbound_id"] == 1


async def test_cb_pick_inbound_not_in_plan(file_db, make_plan):
    """An inbound id not attached to the plan is rejected with an alert."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_inbound(
        cb,
        InboundCB(action="pick", plan_id=plan.id, inbound_id=999),
        state,
    )
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True


async def test_cb_pick_inbound_back_returns_to_plan_list(file_db, make_plan):
    """`back` callback returns user to the plan-list step."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        await make_plan(conn)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_inbound_back(cb, state)
    state.set_state.assert_awaited()
    cb.message.edit_text.assert_awaited()


# ---------------------------------------------------------------------- #
# Promo entry on the buy flow
# ---------------------------------------------------------------------- #


async def test_cb_apply_promo(file_db, make_plan):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_apply_promo(
        cb, BuyCB(action="apply_promo", plan_id=plan.id, inbound_id=1), state
    )
    cb.message.edit_text.assert_awaited()
    # The pinned inbound is preserved into the FSM.
    last = state.update_data.await_args.kwargs
    assert last["inbound_id"] == 1


async def test_msg_promo_code_valid(file_db, make_plan, make_promo, monkeypatch):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn)
        promo = await make_promo(conn, code="GOOD")
        user = _user(user_id=1)

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    msg = MagicMock()
    msg.text = "good"
    msg.answer = AsyncMock()
    state = _state({"plan_id": plan.id, "inbound_id": 1})

    # Insert user into DB so promo's "already redeemed" check works.
    async with get_conn() as conn:
        from app.db.repos.users import create

        u = await create(conn, tg_id=user.tg_id, username="u", first_name="X")

    await buy_module.msg_promo_code(msg, state, user=u)
    msg.answer.assert_awaited()
    state.update_data.assert_awaited()


async def test_msg_promo_code_invalid(file_db, make_plan):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn)
        from app.db.repos.users import create as ucreate

        u = await ucreate(conn, tg_id=1, username="u", first_name="X")

    msg = MagicMock()
    msg.text = "bogus"
    msg.answer = AsyncMock()
    state = _state({"plan_id": plan.id, "inbound_id": 1})
    await buy_module.msg_promo_code(msg, state, user=u)
    msg.answer.assert_awaited()


async def test_msg_promo_code_no_user(file_db):
    msg = MagicMock()
    msg.text = "x"
    msg.answer = AsyncMock()
    state = _state()
    await buy_module.msg_promo_code(msg, state, user=None)
    msg.answer.assert_awaited()


async def test_msg_promo_code_plan_unavailable(file_db, make_plan):
    """If the plan got deactivated between selection and promo input."""
    from app.db.engine import get_conn
    from app.db.repos import plans as plans_repo
    from app.db.repos.users import create as ucreate

    async with get_conn() as conn:
        plan = await make_plan(conn)
        await plans_repo.deactivate(conn, plan.id)
        u = await ucreate(conn, tg_id=1, username="u", first_name="X")

    msg = MagicMock()
    msg.text = "any"
    msg.answer = AsyncMock()
    state = _state({"plan_id": plan.id})
    await buy_module.msg_promo_code(msg, state, user=u)
    state.clear.assert_awaited()


# ---------------------------------------------------------------------- #
# cb_confirm — send invoice (now requires a valid inbound_id)
# ---------------------------------------------------------------------- #


async def test_cb_confirm_sends_invoice(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, price_stars=42, inbound_ids=[1])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=999)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(action="confirm", plan_id=plan.id, promo_id=0, inbound_id=1),
        state,
        mock_bot,
    )
    mock_bot.send_invoice.assert_awaited()
    kwargs = mock_bot.send_invoice.call_args.kwargs
    assert kwargs["currency"] == "XTR"
    assert kwargs["prices"][0].amount == 42
    # Payload embeds the chosen inbound_id.
    data = json.loads(kwargs["payload"])
    assert data["i"] == 1


async def test_cb_confirm_inbound_not_in_plan(file_db, make_plan, mock_bot, monkeypatch):
    """A confirm with an inbound that does NOT belong to the plan triggers
    the recovery path: alert + route back to inbound selection (no invoice).
    """
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    # The recovery path calls list_user_inbounds — return one matching the plan.
    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=1)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(action="confirm", plan_id=plan.id, inbound_id=999),
        state,
        mock_bot,
    )
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True
    # No invoice was sent because the inbound was invalid.
    mock_bot.send_invoice.assert_not_awaited()


async def test_cb_confirm_invalid_plan(file_db, mock_bot):
    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=1)
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb, BuyCB(action="confirm", plan_id=999, inbound_id=1), state, mock_bot
    )
    cb.answer.assert_awaited()
    mock_bot.send_invoice.assert_not_awaited()


async def test_cb_confirm_no_chat_id(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    cb = MagicMock()
    cb.message = None
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(action="confirm", plan_id=plan.id, inbound_id=1),
        state,
        mock_bot,
    )
    cb.answer.assert_awaited()
    mock_bot.send_invoice.assert_not_awaited()


# ---------------------------------------------------------------------- #
# Pre-checkout
# ---------------------------------------------------------------------- #


async def test_pre_checkout_ok(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    mock_bot.answer_pre_checkout_query.assert_awaited()
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is True


async def test_pre_checkout_bad_payload(file_db, mock_bot):
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = "{not-json"
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_plan_deactivated(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn
    from app.db.repos import plans as plans_repo

    async with get_conn() as conn:
        plan = await make_plan(conn)
        await plans_repo.deactivate(conn, plan.id)
    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_promo_invalid(file_db, make_plan, make_promo, mock_bot):
    from app.db.engine import get_conn
    from app.db.repos import promos as promos_repo

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])
        promo = await make_promo(conn, code="X")
        await promos_repo.deactivate(conn, promo.id)
    payload = json.dumps({"p": plan.id, "r": promo.id, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_inbound_not_in_plan(file_db, make_plan, mock_bot):
    """A payload carrying an inbound_id not attached to the plan → ok=False."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    payload = json.dumps({"p": plan.id, "r": None, "i": 999})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_legacy_payload_uses_default_inbound(
    file_db, make_plan, mock_bot
):
    """A legacy payload without 'i' falls back to settings.XUI_INBOUND_ID."""
    from app.db.engine import get_conn

    # Make sure the default inbound matches the plan's attached set so
    # the fallback succeeds.
    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[int(settings.XUI_INBOUND_ID)])

    payload = json.dumps({"plan_id": plan.id, "promo_id": None})  # legacy keys
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is True


async def test_pre_checkout_missing_plan(file_db, mock_bot):
    """pre_checkout with a non-existent plan_id returns ok=False."""
    payload = json.dumps({"p": 9999, "r": None, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


# ---------------------------------------------------------------------- #
# successful_payment
# ---------------------------------------------------------------------- #


async def test_successful_payment_happy_path(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[1])

    xui = AsyncMock()
    xui.request_json = AsyncMock(return_value={"id": "u"})
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    # Patch deliver_keys to skip the real inbound fetch.
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="charge-1",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    # Payment recorded.
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "charge-1")
    assert rec is not None
    assert rec.stars_amount == plan.price_stars


async def test_successful_payment_legacy_payload_falls_back_to_default_inbound(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """A legacy payload without 'i' triggers the fallback path (default inbound)."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[int(settings.XUI_INBOUND_ID)])

    xui = AsyncMock()
    xui.request_json = AsyncMock(return_value={"id": "u"})
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    # Legacy payload uses long keys plan_id/promo_id, no `i`.
    payload = json.dumps({"plan_id": plan.id, "promo_id": None})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="legacy-1",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "legacy-1")
    assert rec is not None
    # The subscription was provisioned on the fallback inbound.
    assert rec.subscription_id is not None


async def test_successful_payment_idempotent(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """A duplicate charge_id is short-circuited (no second sub)."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn)
        await payments_repo.create(
            conn,
            user_id=user.id,
            subscription_id=None,
            telegram_charge_id="dup-charge",
            stars_amount=10,
            plan_id=plan.id,
            promo_id=None,
        )

    xui = AsyncMock()
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="dup-charge",
        total_amount=20,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    # No new payment row added.
    async with get_conn() as conn:
        cur = await conn.execute(
            "SELECT COUNT(*) FROM payments WHERE telegram_charge_id='dup-charge'"
        )
        n = (await cur.fetchone())[0]
    assert n == 1
    # xui.request_json should not have been called (we short-circuited).
    xui.request_json.assert_not_called()


async def test_successful_payment_bad_payload(
    file_db, make_user, mock_bot, monkeypatch
):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)

    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c1",
        total_amount=10,
        invoice_payload="{garbage",
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    msg.answer.assert_awaited()


async def test_successful_payment_no_user(file_db, mock_bot):
    msg = MagicMock()
    msg.successful_payment = MagicMock()
    await buy_module.on_successful_payment(msg, mock_bot, user=None)
    # Should silently return.


async def test_successful_payment_xui_fail_records_payment(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """If xui.add_client fails, payment is still recorded with subscription_id=None."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[1])

    xui = AsyncMock()
    xui.request_json = AsyncMock(side_effect=XuiError("down"))
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-xui-fail",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "c-xui-fail")
    assert rec is not None
    assert rec.subscription_id is None
    # User got the "we'll activate manually" message.
    msg.answer.assert_awaited()


async def test_successful_payment_with_promo_redemption(
    file_db, make_user, make_plan, make_promo, mock_bot, monkeypatch
):
    """successful_payment + promo → promo redeemed via service."""
    from app.db.engine import get_conn
    from app.db.repos import promos as promos_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[1])
        promo = await make_promo(conn, code="SAVE", max_uses=10)

    xui = AsyncMock()
    xui.request_json = AsyncMock(return_value={"id": "u"})
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": promo.id, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-prm",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        refreshed = await promos_repo.get(conn, promo.id)
    assert refreshed.used_count == 1


async def test_successful_payment_plan_deleted(
    file_db, make_user, mock_bot, monkeypatch
):
    """If plan referenced in payload is missing → record payment, alert user."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)

    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-noplan",
        total_amount=20,
        invoice_payload=json.dumps({"p": 999, "r": None, "i": 1}),
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "c-noplan")
    assert rec is not None
    msg.answer.assert_awaited()


# ---------------------------------------------------------------------- #
# _format_confirm — extend vs new card
# ---------------------------------------------------------------------- #


def _make_sub_obj(sub_id: int = 7, user_id: int = 1, inbound_id: int = 1):
    """Build an in-memory Subscription stand-in for _format_confirm tests."""
    from app.db.repos.subscriptions import Subscription

    return Subscription(
        id=sub_id,
        user_id=user_id,
        xui_inbound_id=inbound_id,
        xui_client_uuid="uuid",
        xui_client_email="email",
        xui_sub_id="subid",
        expires_at="2026-06-01 00:00:00",
        created_at="2026-05-01 00:00:00",
        plan_id=None,
        status="active",
    )


def test_format_confirm_renders_extending_card():
    """extending_sub set → card uses '🔄 Продление подписки #N' header and shows new expiry."""
    from app.db.repos.plans import Plan

    plan = Plan(id=1, title="T", days=30, price_stars=100, traffic_gb=0,
                is_active=True, created_at="2025")
    sub = _make_sub_obj(sub_id=7, inbound_id=1)
    text = buy_module._format_confirm(
        plan, promo=None, inbound_remark="DE", extending_sub=sub
    )
    assert "Продление подписки #7" in text
    assert "DE" in text
    # Expiry was pushed forward by plan.days (30) → 2026-07-01.
    assert "2026-07-01" in text
    # New-card phrasing must not leak into the extend card.
    assert "Новая подписка" not in text


def test_format_confirm_renders_new_card():
    """extending_sub=None → card uses '🆕 Новая подписка' header."""
    from app.db.repos.plans import Plan

    plan = Plan(id=1, title="T", days=30, price_stars=100, traffic_gb=0,
                is_active=True, created_at="2025")
    text = buy_module._format_confirm(
        plan, promo=None, inbound_remark="DE", extending_sub=None
    )
    assert "Новая подписка" in text
    assert "DE" in text
    # No "Продление подписки" wording on the new card.
    assert "Продление" not in text


# ---------------------------------------------------------------------- #
# cb_open — action screen vs direct plan list
# ---------------------------------------------------------------------- #


async def test_cb_open_shows_action_screen_when_active_sub_exists(
    file_db, make_user, make_subscription, make_plan, monkeypatch
):
    """User with at least one active sub → state=choosing_action + buy_action_kb."""
    from app.db.engine import get_conn
    from app.states.user import BuyFlow

    async with get_conn() as conn:
        u = await make_user(conn, tg_id=42)
        await make_plan(conn, inbound_ids=[1])
        await make_subscription(conn, user_id=u.id, xui_inbound_id=1)

    # Panel returns matching remark — exercises the happy path.
    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_open(cb, state, user=u)

    state.set_state.assert_awaited_with(BuyFlow.choosing_action)
    cb.message.edit_text.assert_awaited()
    # Rendered card mentions "активные подписки" copy.
    args, kwargs = cb.message.edit_text.call_args
    assert "Выберите действие" in args[0]


async def test_cb_open_skips_action_screen_when_no_active(
    file_db, make_user, make_plan
):
    """User without active subs → goes straight to choosing_plan + plans_kb."""
    from app.db.engine import get_conn
    from app.states.user import BuyFlow

    async with get_conn() as conn:
        u = await make_user(conn, tg_id=43)
        await make_plan(conn, inbound_ids=[1])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_open(cb, state, user=u)

    state.set_state.assert_awaited_with(BuyFlow.choosing_plan)
    cb.message.edit_text.assert_awaited()
    args, kwargs = cb.message.edit_text.call_args
    assert "Выберите тариф" in args[0]


# ---------------------------------------------------------------------- #
# cb_pick_action_extend / new
# ---------------------------------------------------------------------- #


async def test_cb_pick_action_extend_sets_fsm_and_jumps_to_plan_list(
    file_db, make_user, make_subscription, make_plan
):
    """Extend action → FSM gets sub_id+inbound_id, state set to choosing_plan."""
    from app.db.engine import get_conn
    from app.states.user import BuyFlow

    async with get_conn() as conn:
        u = await make_user(conn, tg_id=10)
        await make_plan(conn, inbound_ids=[1])
        sub = await make_subscription(conn, user_id=u.id, xui_inbound_id=5)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_action_extend(
        cb, BuyCB(action="extend", sub_id=sub.id), state, user=u
    )

    last = state.update_data.await_args.kwargs
    assert last["sub_id"] == sub.id
    assert last["inbound_id"] == 5
    # The handler ends in choosing_plan (via _send_plan_list).
    state.set_state.assert_any_await(BuyFlow.choosing_plan)


async def test_cb_pick_action_extend_rejects_foreign_sub(
    file_db, make_user, make_subscription
):
    """Ownership check: extend with another user's sub_id is rejected."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        owner = await make_user(conn, tg_id=20)
        other = await make_user(conn, tg_id=21)
        sub = await make_subscription(conn, user_id=owner.id, xui_inbound_id=1)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_action_extend(
        cb, BuyCB(action="extend", sub_id=sub.id), state, user=other
    )
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True
    # FSM was not advanced.
    state.set_state.assert_not_awaited()


async def test_cb_pick_action_new_clears_fsm_and_jumps_to_plan_list(
    file_db, make_plan
):
    """New action → FSM cleared (sub_id=0), state set to choosing_plan."""
    from app.db.engine import get_conn
    from app.states.user import BuyFlow

    async with get_conn() as conn:
        await make_plan(conn, inbound_ids=[1])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_action_new(cb, state)

    state.clear.assert_awaited()
    state.set_state.assert_any_await(BuyFlow.choosing_plan)


# ---------------------------------------------------------------------- #
# cb_pick_plan — extend branch skips inbound selection
# ---------------------------------------------------------------------- #


async def test_cb_pick_plan_extend_skips_inbound_selection(
    file_db, make_user, make_subscription, make_plan, monkeypatch
):
    """Even for a multi-inbound plan, sub_id>0 in FSM → state=confirming directly."""
    from app.db.engine import get_conn
    from app.states.user import BuyFlow

    async with get_conn() as conn:
        u = await make_user(conn, tg_id=30)
        # Plan attached to inbounds {1, 2}; existing sub is on inbound 5
        # (intentionally NOT in the plan's allow-list to prove the
        # extend branch bypasses the check).
        plan = await make_plan(conn, inbound_ids=[1, 2])
        sub = await make_subscription(conn, user_id=u.id, xui_inbound_id=5)

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1, 2, 5)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state({"sub_id": sub.id, "inbound_id": 5})
    await buy_module.cb_pick_plan(
        cb, BuyCB(action="plan", plan_id=plan.id), state, user=u
    )

    state.set_state.assert_awaited_with(BuyFlow.confirming)
    # Card uses the extend header.
    args, kwargs = cb.message.edit_text.call_args
    assert f"Продление подписки #{sub.id}" in args[0]


# ---------------------------------------------------------------------- #
# cb_confirm — extend flow
# ---------------------------------------------------------------------- #


async def test_cb_confirm_extend_passes_sub_id_in_payload(
    file_db, make_user, make_subscription, make_plan, mock_bot
):
    """Confirm with sub_id>0 → invoice payload carries 's' = sub.id."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        u = await make_user(conn, tg_id=44)
        plan = await make_plan(conn, price_stars=50, inbound_ids=[1])
        sub = await make_subscription(conn, user_id=u.id, xui_inbound_id=5)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=777)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(
            action="confirm", plan_id=plan.id, promo_id=0,
            inbound_id=5, sub_id=sub.id,
        ),
        state,
        mock_bot,
        user=u,
    )
    mock_bot.send_invoice.assert_awaited()
    kwargs = mock_bot.send_invoice.call_args.kwargs
    data = json.loads(kwargs["payload"])
    assert data.get("s") == sub.id
    assert data.get("i") == 5


async def test_cb_confirm_extend_skips_allow_list(
    file_db, make_user, make_subscription, make_plan, mock_bot
):
    """Extend: inbound NOT in plan's allow-list still produces a sent invoice."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        u = await make_user(conn, tg_id=45)
        plan = await make_plan(conn, inbound_ids=[1])  # 5 is NOT attached
        sub = await make_subscription(conn, user_id=u.id, xui_inbound_id=5)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=777)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(
            action="confirm", plan_id=plan.id, promo_id=0,
            inbound_id=5, sub_id=sub.id,
        ),
        state,
        mock_bot,
        user=u,
    )
    # Invoice was sent (allow-list check skipped).
    mock_bot.send_invoice.assert_awaited()


async def test_cb_confirm_extend_rejects_foreign_sub(
    file_db, make_user, make_subscription, make_plan, mock_bot
):
    """Defence-in-depth: confirm with another user's sub → no invoice."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        owner = await make_user(conn, tg_id=46)
        thief = await make_user(conn, tg_id=47)
        plan = await make_plan(conn, inbound_ids=[1])
        sub = await make_subscription(conn, user_id=owner.id, xui_inbound_id=1)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=1)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(
            action="confirm", plan_id=plan.id, promo_id=0,
            inbound_id=1, sub_id=sub.id,
        ),
        state,
        mock_bot,
        user=thief,
    )
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True
    mock_bot.send_invoice.assert_not_awaited()


# ---------------------------------------------------------------------- #
# on_pre_checkout — extend ownership validation
# ---------------------------------------------------------------------- #


async def test_on_pre_checkout_extend_validates_ownership(
    file_db, make_user, make_subscription, make_plan, mock_bot
):
    """pre_checkout with sub_id of foreign user → ok=False; with own active → ok=True."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        owner = await make_user(conn, tg_id=50)
        other = await make_user(conn, tg_id=51)
        plan = await make_plan(conn, inbound_ids=[1])
        sub = await make_subscription(conn, user_id=owner.id, xui_inbound_id=5)

    # foreign user attempt
    payload = json.dumps({"p": plan.id, "r": None, "i": 5, "s": sub.id})
    q = MagicMock()
    q.id = "qid-foreign"
    q.from_user = MagicMock(id=other.tg_id)
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False

    # owner attempt with same payload
    mock_bot.answer_pre_checkout_query.reset_mock()
    q2 = MagicMock()
    q2.id = "qid-owner"
    q2.from_user = MagicMock(id=owner.tg_id)
    q2.invoice_payload = payload
    await buy_module.on_pre_checkout(q2, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is True


async def test_on_pre_checkout_extend_skips_allow_list(
    file_db, make_user, make_subscription, make_plan, mock_bot
):
    """Extend pre_checkout: inbound NOT in allow-list still ok=True."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        owner = await make_user(conn, tg_id=52)
        plan = await make_plan(conn, inbound_ids=[1])
        sub = await make_subscription(conn, user_id=owner.id, xui_inbound_id=99)

    payload = json.dumps({"p": plan.id, "r": None, "i": 99, "s": sub.id})
    q = MagicMock()
    q.id = "qid-bypass"
    q.from_user = MagicMock(id=owner.tg_id)
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is True


# ---------------------------------------------------------------------- #
# on_successful_payment — extend_sub_id passthrough
# ---------------------------------------------------------------------- #


async def test_on_successful_payment_extend_calls_service_with_extend_sub_id(
    file_db, make_user, make_subscription, make_plan, mock_bot, monkeypatch
):
    """Payload with s=N → subs_service.create_or_extend(extend_sub_id=N)."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=60)
        plan = await make_plan(conn, inbound_ids=[1])
        sub = await make_subscription(conn, user_id=user.id, xui_inbound_id=1)

    xui = AsyncMock()
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    create_or_extend = AsyncMock(return_value=sub)
    monkeypatch.setattr(
        buy_module.subs_service, "create_or_extend", create_or_extend
    )

    payload = json.dumps({"p": plan.id, "r": None, "i": 1, "s": sub.id})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-ext-1",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    create_or_extend.assert_awaited()
    kwargs = create_or_extend.call_args.kwargs
    assert kwargs["extend_sub_id"] == sub.id


async def test_on_successful_payment_new_calls_service_with_extend_sub_id_none(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """Payload without 's' → subs_service.create_or_extend(extend_sub_id=None)."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=61)
        plan = await make_plan(conn, inbound_ids=[1])

    xui = AsyncMock()
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    create_or_extend = AsyncMock()
    create_or_extend.return_value = None  # service hiccup is fine for this test
    monkeypatch.setattr(
        buy_module.subs_service, "create_or_extend", create_or_extend
    )

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})  # no "s"
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-new-1",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    create_or_extend.assert_awaited()
    kwargs = create_or_extend.call_args.kwargs
    assert kwargs["extend_sub_id"] is None
