"""Tests for :mod:`app.handlers.user.buy` — buy flow + inbound selection."""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, MagicMock

import pytest

from app.config import settings
from app.db.repos.users import User
from app.handlers.user import buy as buy_module
from app.keyboards.user import BuyCB, InboundCB
from app.services.inbounds import InboundOption
from app.xui import XuiError


def _user(user_id=1, tg_id=1, is_admin=False):
    return User(
        id=user_id, tg_id=tg_id, username="u", first_name="X",
        is_admin=is_admin, created_at="2025",
    )


def _state(data: dict | None = None):
    """Build a mock FSMContext, optionally pre-seeded with state data."""
    s = AsyncMock()
    s.get_data = AsyncMock(return_value=data or {})
    s.update_data = AsyncMock()
    s.set_state = AsyncMock()
    s.clear = AsyncMock()
    return s


def _stub_inbounds(*ids: int) -> list[InboundOption]:
    """Build an `InboundOption` list with the given ids (remarks autogenerated)."""
    return [
        InboundOption(id=i, remark=f"srv-{i}", port=443 + i, enabled=True)
        for i in ids
    ]


@pytest.fixture(autouse=True)
def _clear_inbounds_cache():
    """Drop the inbounds service cache between tests to avoid leakage."""
    from app.services import inbounds as inb

    inb.clear_cache()
    yield
    inb.clear_cache()


# ---------------------------------------------------------------------- #
# cb_open — show plan list
# ---------------------------------------------------------------------- #


async def test_cb_open_no_plans(file_db, mock_bot):
    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_open(cb, state)
    cb.message.edit_text.assert_awaited()


async def test_cb_open_with_plans(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        await make_plan(conn)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_open(cb, state)
    cb.message.edit_text.assert_awaited()


# ---------------------------------------------------------------------- #
# cb_pick_plan — single vs multi inbound routing
# ---------------------------------------------------------------------- #


async def test_cb_pick_plan_single_inbound_skips_to_confirm(
    file_db, make_plan, monkeypatch
):
    """A plan with exactly one inbound auto-skips the selection step."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    # Panel returns one matching inbound — the resolver looks up its remark.
    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)

    # State writes: inbound_id is pinned and no options stored (single-inbound path).
    state.update_data.assert_awaited()
    last_kwargs = state.update_data.await_args.kwargs
    assert last_kwargs["inbound_id"] == 1
    assert last_kwargs.get("inbound_options") is None
    # The confirmation card was rendered (edit_text called).
    cb.message.edit_text.assert_awaited()


async def test_cb_pick_plan_multi_inbound_shows_selector(
    file_db, make_plan, monkeypatch
):
    """A plan with N>1 inbounds enters choosing_inbound with the multi-option kb."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1, 2, 99)),  # 99 is not in plan
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)

    # Stored options should be filtered to inbound ids 1 and 2 only.
    last_kwargs = state.update_data.await_args.kwargs
    stored_options = last_kwargs["inbound_options"]
    assert {o["id"] for o in stored_options} == {1, 2}
    assert last_kwargs["inbound_id"] == 0  # not yet picked


async def test_cb_pick_plan_no_inbounds_misconfigured(file_db, make_plan, monkeypatch):
    """A plan with zero inbounds yields an alert and no state advance."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[])  # explicit: no inbounds

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)
    # Alert was shown.
    cb.answer.assert_awaited()
    args, kwargs = cb.answer.call_args
    assert kwargs.get("show_alert") is True


async def test_cb_pick_plan_with_existing_promo_in_state(
    file_db, make_plan, make_promo, monkeypatch
):
    """Picking a plan preserves a promo_id already in FSM."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])
        promo = await make_promo(conn, code="X")

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state({"promo_id": promo.id})
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)
    last_kwargs = state.update_data.await_args.kwargs
    assert last_kwargs["promo_id"] == promo.id


async def test_cb_pick_plan_unknown_or_inactive(file_db):
    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    cb_data = BuyCB(action="plan", plan_id=999)
    await buy_module.cb_pick_plan(cb, cb_data, state)
    cb.answer.assert_awaited_once()


async def test_cb_pick_plan_xui_unavailable_multi(file_db, make_plan, monkeypatch):
    """When the panel fails on a multi-inbound plan the user sees an alert."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(side_effect=XuiError("down")),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_plan(cb, BuyCB(action="plan", plan_id=plan.id), state)
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True


# ---------------------------------------------------------------------- #
# cb_pick_inbound — inbound selection step
# ---------------------------------------------------------------------- #


async def test_cb_pick_inbound_valid(file_db, make_plan):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state({"inbound_options": [{"id": 1, "remark": "DE", "port": 443, "enabled": True}]})
    await buy_module.cb_pick_inbound(
        cb,
        InboundCB(action="pick", plan_id=plan.id, inbound_id=1),
        state,
    )
    last = state.update_data.await_args.kwargs
    assert last["inbound_id"] == 1


async def test_cb_pick_inbound_not_in_plan(file_db, make_plan):
    """An inbound id not attached to the plan is rejected with an alert."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1, 2])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_inbound(
        cb,
        InboundCB(action="pick", plan_id=plan.id, inbound_id=999),
        state,
    )
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True


async def test_cb_pick_inbound_back_returns_to_plan_list(file_db, make_plan):
    """`back` callback returns user to the plan-list step."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        await make_plan(conn)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_pick_inbound_back(cb, state)
    state.set_state.assert_awaited()
    cb.message.edit_text.assert_awaited()


# ---------------------------------------------------------------------- #
# Promo entry on the buy flow
# ---------------------------------------------------------------------- #


async def test_cb_apply_promo(file_db, make_plan):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn)

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_apply_promo(
        cb, BuyCB(action="apply_promo", plan_id=plan.id, inbound_id=1), state
    )
    cb.message.edit_text.assert_awaited()
    # The pinned inbound is preserved into the FSM.
    last = state.update_data.await_args.kwargs
    assert last["inbound_id"] == 1


async def test_msg_promo_code_valid(file_db, make_plan, make_promo, monkeypatch):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn)
        promo = await make_promo(conn, code="GOOD")
        user = _user(user_id=1)

    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    msg = MagicMock()
    msg.text = "good"
    msg.answer = AsyncMock()
    state = _state({"plan_id": plan.id, "inbound_id": 1})

    # Insert user into DB so promo's "already redeemed" check works.
    async with get_conn() as conn:
        from app.db.repos.users import create

        u = await create(conn, tg_id=user.tg_id, username="u", first_name="X")

    await buy_module.msg_promo_code(msg, state, user=u)
    msg.answer.assert_awaited()
    state.update_data.assert_awaited()


async def test_msg_promo_code_invalid(file_db, make_plan):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn)
        from app.db.repos.users import create as ucreate

        u = await ucreate(conn, tg_id=1, username="u", first_name="X")

    msg = MagicMock()
    msg.text = "bogus"
    msg.answer = AsyncMock()
    state = _state({"plan_id": plan.id, "inbound_id": 1})
    await buy_module.msg_promo_code(msg, state, user=u)
    msg.answer.assert_awaited()


async def test_msg_promo_code_no_user(file_db):
    msg = MagicMock()
    msg.text = "x"
    msg.answer = AsyncMock()
    state = _state()
    await buy_module.msg_promo_code(msg, state, user=None)
    msg.answer.assert_awaited()


async def test_msg_promo_code_plan_unavailable(file_db, make_plan):
    """If the plan got deactivated between selection and promo input."""
    from app.db.engine import get_conn
    from app.db.repos import plans as plans_repo
    from app.db.repos.users import create as ucreate

    async with get_conn() as conn:
        plan = await make_plan(conn)
        await plans_repo.deactivate(conn, plan.id)
        u = await ucreate(conn, tg_id=1, username="u", first_name="X")

    msg = MagicMock()
    msg.text = "any"
    msg.answer = AsyncMock()
    state = _state({"plan_id": plan.id})
    await buy_module.msg_promo_code(msg, state, user=u)
    state.clear.assert_awaited()


# ---------------------------------------------------------------------- #
# cb_confirm — send invoice (now requires a valid inbound_id)
# ---------------------------------------------------------------------- #


async def test_cb_confirm_sends_invoice(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, price_stars=42, inbound_ids=[1])

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=999)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(action="confirm", plan_id=plan.id, promo_id=0, inbound_id=1),
        state,
        mock_bot,
    )
    mock_bot.send_invoice.assert_awaited()
    kwargs = mock_bot.send_invoice.call_args.kwargs
    assert kwargs["currency"] == "XTR"
    assert kwargs["prices"][0].amount == 42
    # Payload embeds the chosen inbound_id.
    data = json.loads(kwargs["payload"])
    assert data["i"] == 1


async def test_cb_confirm_inbound_not_in_plan(file_db, make_plan, mock_bot, monkeypatch):
    """A confirm with an inbound that does NOT belong to the plan triggers
    the recovery path: alert + route back to inbound selection (no invoice).
    """
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    # The recovery path calls list_user_inbounds — return one matching the plan.
    monkeypatch.setattr(
        buy_module, "get_xui_client", AsyncMock(return_value=AsyncMock())
    )
    monkeypatch.setattr(
        buy_module, "list_user_inbounds",
        AsyncMock(return_value=_stub_inbounds(1)),
    )

    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=1)
    cb.message.edit_text = AsyncMock()
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(action="confirm", plan_id=plan.id, inbound_id=999),
        state,
        mock_bot,
    )
    cb.answer.assert_awaited()
    assert cb.answer.call_args.kwargs.get("show_alert") is True
    # No invoice was sent because the inbound was invalid.
    mock_bot.send_invoice.assert_not_awaited()


async def test_cb_confirm_invalid_plan(file_db, mock_bot):
    cb = MagicMock()
    cb.message = MagicMock()
    cb.message.chat = MagicMock(id=1)
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb, BuyCB(action="confirm", plan_id=999, inbound_id=1), state, mock_bot
    )
    cb.answer.assert_awaited()
    mock_bot.send_invoice.assert_not_awaited()


async def test_cb_confirm_no_chat_id(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    cb = MagicMock()
    cb.message = None
    cb.answer = AsyncMock()
    state = _state()
    await buy_module.cb_confirm(
        cb,
        BuyCB(action="confirm", plan_id=plan.id, inbound_id=1),
        state,
        mock_bot,
    )
    cb.answer.assert_awaited()
    mock_bot.send_invoice.assert_not_awaited()


# ---------------------------------------------------------------------- #
# Pre-checkout
# ---------------------------------------------------------------------- #


async def test_pre_checkout_ok(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    mock_bot.answer_pre_checkout_query.assert_awaited()
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is True


async def test_pre_checkout_bad_payload(file_db, mock_bot):
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = "{not-json"
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_plan_deactivated(file_db, make_plan, mock_bot):
    from app.db.engine import get_conn
    from app.db.repos import plans as plans_repo

    async with get_conn() as conn:
        plan = await make_plan(conn)
        await plans_repo.deactivate(conn, plan.id)
    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_promo_invalid(file_db, make_plan, make_promo, mock_bot):
    from app.db.engine import get_conn
    from app.db.repos import promos as promos_repo

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])
        promo = await make_promo(conn, code="X")
        await promos_repo.deactivate(conn, promo.id)
    payload = json.dumps({"p": plan.id, "r": promo.id, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_inbound_not_in_plan(file_db, make_plan, mock_bot):
    """A payload carrying an inbound_id not attached to the plan → ok=False."""
    from app.db.engine import get_conn

    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[1])

    payload = json.dumps({"p": plan.id, "r": None, "i": 999})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


async def test_pre_checkout_legacy_payload_uses_default_inbound(
    file_db, make_plan, mock_bot
):
    """A legacy payload without 'i' falls back to settings.XUI_INBOUND_ID."""
    from app.db.engine import get_conn

    # Make sure the default inbound matches the plan's attached set so
    # the fallback succeeds.
    async with get_conn() as conn:
        plan = await make_plan(conn, inbound_ids=[int(settings.XUI_INBOUND_ID)])

    payload = json.dumps({"plan_id": plan.id, "promo_id": None})  # legacy keys
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is True


async def test_pre_checkout_missing_plan(file_db, mock_bot):
    """pre_checkout with a non-existent plan_id returns ok=False."""
    payload = json.dumps({"p": 9999, "r": None, "i": 1})
    q = MagicMock()
    q.id = "qid"
    q.invoice_payload = payload
    await buy_module.on_pre_checkout(q, mock_bot)
    kwargs = mock_bot.answer_pre_checkout_query.call_args.kwargs
    assert kwargs["ok"] is False


# ---------------------------------------------------------------------- #
# successful_payment
# ---------------------------------------------------------------------- #


async def test_successful_payment_happy_path(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[1])

    xui = AsyncMock()
    xui.request_json = AsyncMock(return_value={"id": "u"})
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    # Patch deliver_keys to skip the real inbound fetch.
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="charge-1",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    # Payment recorded.
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "charge-1")
    assert rec is not None
    assert rec.stars_amount == plan.price_stars


async def test_successful_payment_legacy_payload_falls_back_to_default_inbound(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """A legacy payload without 'i' triggers the fallback path (default inbound)."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[int(settings.XUI_INBOUND_ID)])

    xui = AsyncMock()
    xui.request_json = AsyncMock(return_value={"id": "u"})
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    # Legacy payload uses long keys plan_id/promo_id, no `i`.
    payload = json.dumps({"plan_id": plan.id, "promo_id": None})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="legacy-1",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "legacy-1")
    assert rec is not None
    # The subscription was provisioned on the fallback inbound.
    assert rec.subscription_id is not None


async def test_successful_payment_idempotent(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """A duplicate charge_id is short-circuited (no second sub)."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn)
        await payments_repo.create(
            conn,
            user_id=user.id,
            subscription_id=None,
            telegram_charge_id="dup-charge",
            stars_amount=10,
            plan_id=plan.id,
            promo_id=None,
        )

    xui = AsyncMock()
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="dup-charge",
        total_amount=20,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    # No new payment row added.
    async with get_conn() as conn:
        cur = await conn.execute(
            "SELECT COUNT(*) FROM payments WHERE telegram_charge_id='dup-charge'"
        )
        n = (await cur.fetchone())[0]
    assert n == 1
    # xui.request_json should not have been called (we short-circuited).
    xui.request_json.assert_not_called()


async def test_successful_payment_bad_payload(
    file_db, make_user, mock_bot, monkeypatch
):
    from app.db.engine import get_conn

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)

    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c1",
        total_amount=10,
        invoice_payload="{garbage",
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    msg.answer.assert_awaited()


async def test_successful_payment_no_user(file_db, mock_bot):
    msg = MagicMock()
    msg.successful_payment = MagicMock()
    await buy_module.on_successful_payment(msg, mock_bot, user=None)
    # Should silently return.


async def test_successful_payment_xui_fail_records_payment(
    file_db, make_user, make_plan, mock_bot, monkeypatch
):
    """If xui.add_client fails, payment is still recorded with subscription_id=None."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[1])

    xui = AsyncMock()
    xui.request_json = AsyncMock(side_effect=XuiError("down"))
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": None, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-xui-fail",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "c-xui-fail")
    assert rec is not None
    assert rec.subscription_id is None
    # User got the "we'll activate manually" message.
    msg.answer.assert_awaited()


async def test_successful_payment_with_promo_redemption(
    file_db, make_user, make_plan, make_promo, mock_bot, monkeypatch
):
    """successful_payment + promo → promo redeemed via service."""
    from app.db.engine import get_conn
    from app.db.repos import promos as promos_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)
        plan = await make_plan(conn, inbound_ids=[1])
        promo = await make_promo(conn, code="SAVE", max_uses=10)

    xui = AsyncMock()
    xui.request_json = AsyncMock(return_value={"id": "u"})
    monkeypatch.setattr(buy_module, "get_xui_client", AsyncMock(return_value=xui))
    monkeypatch.setattr(buy_module, "deliver_keys", AsyncMock())

    payload = json.dumps({"p": plan.id, "r": promo.id, "i": 1})
    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-prm",
        total_amount=plan.price_stars,
        invoice_payload=payload,
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        refreshed = await promos_repo.get(conn, promo.id)
    assert refreshed.used_count == 1


async def test_successful_payment_plan_deleted(
    file_db, make_user, mock_bot, monkeypatch
):
    """If plan referenced in payload is missing → record payment, alert user."""
    from app.db.engine import get_conn
    from app.db.repos import payments as payments_repo

    async with get_conn() as conn:
        user = await make_user(conn, tg_id=1)

    msg = MagicMock()
    msg.chat = MagicMock(id=1)
    msg.answer = AsyncMock()
    msg.successful_payment = MagicMock(
        telegram_payment_charge_id="c-noplan",
        total_amount=20,
        invoice_payload=json.dumps({"p": 999, "r": None, "i": 1}),
    )
    await buy_module.on_successful_payment(msg, mock_bot, user=user)
    async with get_conn() as conn:
        rec = await payments_repo.get_by_charge_id(conn, "c-noplan")
    assert rec is not None
    msg.answer.assert_awaited()


# ---------------------------------------------------------------------- #
# _format_confirm — active-subscription warning
# ---------------------------------------------------------------------- #


def test_format_confirm_warning_when_active_sub_exists():
    """If user already has an active sub, the confirmation text warns them."""
    from app.db.repos.plans import Plan

    plan = Plan(id=1, title="T", days=30, price_stars=100, traffic_gb=0,
                is_active=True, created_at="2025")
    text = buy_module._format_confirm(
        plan, promo=None, inbound_remark="DE", has_active_sub=True
    )
    # Warning text explicitly mentions the inbound is ignored on extend.
    assert "продлена" in text or "не применится" in text


def test_format_confirm_no_warning_when_no_active_sub():
    from app.db.repos.plans import Plan

    plan = Plan(id=1, title="T", days=30, price_stars=100, traffic_gb=0,
                is_active=True, created_at="2025")
    text = buy_module._format_confirm(
        plan, promo=None, inbound_remark="DE", has_active_sub=False
    )
    assert "не применится" not in text
